version: '3.9'

services:
  db:
    image: postgres:16
    container_name: project_helper_db
    volumes:
      - ./postgresdata:/var/lib/postgresql/data
    env_file:
      - ./envs/.env
    ports:
      - 5555:5432
  app:
    build:
      context: .
    container_name: project_helper_app
    volumes:
      - ./app:/project_helper/app
    env_file:
      - ./envs/.env
    depends_on:
      db:
        condition: service_started
    command: bash -c "/project_helper/app/scripts/start.sh"
    ports:
      - 9000:8000

volumes:
  postgresdata:
  app:
