"""add shoppings

Revision ID: 6dca30b36ea2
Revises: d3c4ad28275c
Create Date: 2024-07-31 17:33:44.715969+03:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6dca30b36ea2'
down_revision: Union[str, None] = 'd3c4ad28275c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shopping',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('shopping_list', sa.String(), nullable=False),
    sa.Column('creator_id', sa.UUID(), nullable=False),
    sa.Column('created_date', sa.Date(), nullable=False),
    sa.Column('finish_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shopping')
    # ### end Alembic commands ###
