"""add updated_date to groups

Revision ID: 5716a580105c
Revises: f1b1ffe1fac3
Create Date: 2025-06-06 22:46:03.907960+03:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5716a580105c'
down_revision: Union[str, None] = 'f1b1ffe1fac3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('updated_date', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'updated_date')
    # ### end Alembic commands ###
