"""change passwords storage

Revision ID: aca0cb033738
Revises: 0623a4c85f70
Create Date: 2025-04-21 21:40:45.917747+03:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aca0cb033738'
down_revision: Union[str, None] = '0623a4c85f70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('passwords',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # op.create_foreign_key(None, 'shopping', 'users', ['creator_id'], ['id'])
    # op.create_foreign_key(None, 'tasks', 'users', ['creator_id'], ['id'])
    op.drop_column('users', 'hashed_password')
    # op.create_foreign_key(None, 'users_friends_association_table', 'users', ['user_id'], ['id'])
    # op.create_foreign_key(None, 'users_friends_association_table', 'users', ['friend_id'], ['id'])
    # op.create_foreign_key(None, 'users_shoppings_association_table', 'users', ['user_id'], ['id'])
    # op.create_foreign_key(None, 'users_tasks_association_table', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(None, 'users_tasks_association_table', type_='foreignkey')
    # op.drop_constraint(None, 'users_shoppings_association_table', type_='foreignkey')
    # op.drop_constraint(None, 'users_friends_association_table', type_='foreignkey')
    # op.drop_constraint(None, 'users_friends_association_table', type_='foreignkey')
    op.add_column('users', sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=False))
    # op.drop_constraint(None, 'tasks', type_='foreignkey')
    # op.drop_constraint(None, 'shopping', type_='foreignkey')
    op.drop_table('passwords')
    # ### end Alembic commands ###
