"""add users-shoppings many-to-many

Revision ID: e4dc1b076a76
Revises: 0016d7216e5a
Create Date: 2025-04-06 18:54:39.146366+03:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4dc1b076a76'
down_revision: Union[str, None] = '0016d7216e5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_shoppings_association_table',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('shopping_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['shopping_id'], ['shopping.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'shopping_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_shoppings_association_table')
    # ### end Alembic commands ###
