"""change association table name

Revision ID: 0016d7216e5a
Revises: f7b40d6f3829
Create Date: 2025-04-06 18:35:06.214547+03:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0016d7216e5a'
down_revision: Union[str, None] = 'f7b40d6f3829'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_tasks_association_table',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'task_id')
    )
    op.drop_table('association_table')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('association_table',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('task_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name='association_table_task_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='association_table_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'task_id', name='association_table_pkey')
    )
    op.drop_table('users_tasks_association_table')
    # ### end Alembic commands ###
